// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
	username,
	hashed_pwd,
	email,
	full_name
) VALUES (
	$1, $2, $3, $4
) RETURNING username, hashed_pwd, email, full_name, created_at, pwd_updated_at
`

type CreateUserParams struct {
	Username  string `json:"username"`
	HashedPwd string `json:"hashed_pwd"`
	Email     string `json:"email"`
	FullName  string `json:"full_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.HashedPwd,
		arg.Email,
		arg.FullName,
	)
	var i User
	err := row.Scan(
		&i.Username,
		&i.HashedPwd,
		&i.Email,
		&i.FullName,
		&i.CreatedAt,
		&i.PwdUpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT username, hashed_pwd, email, full_name, created_at, pwd_updated_at
FROM users
WHERE username = $1
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, username)
	var i User
	err := row.Scan(
		&i.Username,
		&i.HashedPwd,
		&i.Email,
		&i.FullName,
		&i.CreatedAt,
		&i.PwdUpdatedAt,
	)
	return i, err
}
