apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::417441726608:user/github-ci
      username: github-ci
      groups:
        - system:masters

