apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: simple-bank
  region: us-east-2

vpc:
  nat:
    gateway: Disable

managedNodeGroups:
  - name: simple-bank-node
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    volumeSize: 20
    privateNetworking: false
    ssh:
      allow: false
